name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Add the environment variable logging step
      - name: Log environment variables for debugging
        run: |
          echo "VITE_BACKEND_URI: $VITE_BACKEND_URI"
          echo "VITE_OPENAI_API_KEY: $VITE_OPENAI_API_KEY"
          echo "DUMMY_VAR: $DUMMY_VAR"
        env:
          VITE_BACKEND_URI: ${{ secrets.VITE_BACKEND_URI }}
          VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
          DUMMY_VAR: ${{ secrets.DUMMY_VAR }}
          VITE_XX_XXX: xxxx
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_MOSS_093E9111E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
